/*
  Copyright (c) 2013 José Carlos Nieto, http://xiam.menteslibres.org/

  Permission is hereby granted, free of charge, to any person obtaining
  a copy of this software and associated documentation files (the
  "Software"), to deal in the Software without restriction, including
  without limitation the rights to use, copy, modify, merge, publish,
  distribute, sublicense, and/or sell copies of the Software, and to
  permit persons to whom the Software is furnished to do so, subject to
  the following conditions:

  The above copyright notice and this permission notice shall be
  included in all copies or substantial portions of the Software.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
  NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
  LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
  OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
  WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/

package main

import (
	"bytes"
	"testing"
)

func TestCompress(t *testing.T) {

	var s = []string{
		`b.style.cssText="margin:0";c.style.cssText="position:fixed";for(s="ABCDEFG",t=0;s[t];){window[s[t]]=function(t){return function(a,b,c,d,e,i){if(t==5){a.parentNode.appendChild(i=a.cloneNode());i.A=i.getContext("2d");with(i){A.r=A.fillRect;A.f=A.fill;A.p=A.beginPath;A.w=A.arc}}if(t==3){with(a){f(w(b+U,c+U,d,0,R,p(e=createRadialGradient(b,c,d*.1,b,c,d*.8),e.a=e.addColorStop,e.a(0,A(0,0,0,.6),e.a(1,A(0,0,0,0))),a[W]=e)))}}if(t==2){G(c1,G(c3));with(a=c1.A){for(i=V.length-1;i--;){b=V[i];b[3]=.5+P(0,b[1])/Y;f(p(a[W]=A(243,212,69,1)),w(b[0],b[1],1,0,R));D(c3.A,b[0],b[1],(30+U*10)*b[3]);b[0]+=N(b[2])*b[4];b[1]+=O(b[2])*b[4];b[2]+=U*.2}}with(a=c3.A){a.globalCompositeOperation="xor";a[W]=A(0,0,20,.9);p();r(0,0,X,Y);f()}T++}if(t==1){for(b=0;b&&(c=e[0]-a.clientX)*c+(d=e[1]-a.clientY)*d<9e3?(e[2]=-Q*M,e[4]=5):0,e=V[b++];);}return t^6?t^4?t^0?i:"rgba("+[a,b,c,d]+")":Q-.5:a.width=X}}(t++)}with(Math){M=PI;N=cos;O=sin;P=max;Q={valueOf:random}}R=M*2;S=13;T=0;V=[];U={valueOf:E};W="fillStyle";c.width=X=innerWidth;c.height=Y=innerHeight;Z=Y/4;for(c1=F(c,c3=F(c,c2=F(c))),i=0;V[i++]=[Q*X,j=Z+Q*(Y-Z),Q*R,.5+j/Y,.2],i<S;);with(a=c2.A){for(r(0,0,i=X,Y,a[Z]=A(0,0,50,1));i--;f(w(Q*X,Q*Y,1,0,R,p(a[W]="#fff"))));r(0,Z,X,Y,a[W]="#120");for(i=Z;i<2*Y;i+=4){for(k=.1*(1+(i-Z)/Z),j=0;f(moveTo(j,l=i+U*8,p(a[W]=A(0,255,0,.2+Q*.4))),bezierCurveTo(j+U*3,l-9*k*(1+U),j+U*6,l-36*k*(1+U),j+U*9,l-81*k*(1+U))),j<X;j+=(8+U)*k);}}b.onmousemove=B;setInterval(C,S);`,
		`for(b.style.cssText="background:#00c;margin:0",c.style.position="fixed",s="ABCDE",t=0;s[t];)self[s[t]]=function(t){return function(a,b,c,d,e){if(t==4){a.parentNode.appendChild(e=a.cloneNode());e.A=e.getContext("2d");with(e)A.r=A.fillRect,A.f=A.fill,A.p=A.beginPath,A.w=A.arc}if(t==2)with(a=H.A){for(H[c="width"]=I[c]=X,c=0;b=V[c++];){with(b){b.r=.5+P(0,y)/Y;f(p(a[W]="#df0"),w(x,y,1,0,R));d=(30+U*10)*r;with(a=I.A)f(w(x+U,y+U,d,0,R,p(e=createRadialGradient(x,y,d*.1,x,y,d*.8),e[d="addColorStop"](0,A(0,0,0,.6),e[d](1,A(0,0,0,0))),a[W]=e))),c^1?0:f(a.globalCompositeOperation="xor",r(0,0,X,Y,p(a[W]=A(0,0,20,.9))));b.x+=N(z,b.y+=O(z,b.t+=U*.2)*s)*s}}}if(t==1)for(b=0;e=V[b++];)if((c=e.x-a.clientX)*c+(d=e.y-a.clientY)*d<9e3)e.z=-Q*M,e.s=5;return t^3?t^0?e:"rgba("+[a,b,c,d]+")":Q-.5}}(t++);with(Math)M=PI,N=cos,O=sin,P=max,Q={valueOf:random};V=[];S=13;U={valueOf:D};c.width=X=innerWidth;Z=(c.height=Y=innerHeight)/4;with(a=E(c).A){for(m=0,i=Z;i<2*Y;i+=4){if(m<S)V[m++]={x:Q*X,y:j=Z+Q*(Y-Z),z:Q*(R=M*2),s:.4};i^Z?f(w(Q*X,Q*Z,1,0,R,p(a[W]="#fff"))):r(0,Z,X,Y,a[W="fillStyle"]="#120");for(k=.1*i/Z,j=0;f(moveTo(j,l=i+U*8,p(a[W]=A(0,255,0,.2+Q*.4))),bezierCurveTo(j+U*3,l-9*k*(1+U),j+U*6,l-36*k*(1+U),j+U*9,l-81*k*(1+U))),j<X;j+=(8+U)*k);}H=E(c,I=E(c));setInterval(C,S,b.onmousemove=B)}`,
		`for(b.style.cssText="background:#00c;margin:0",c.style.position="fixed",s="ABCDE",t=0;s[t];)self[s[t]]=function(t){return function(a,b,c,d,e){if(t==4){a.parentNode.appendChild(e=a.cloneNode());e.A=e.getContext("2d");with(e)A.r=A.fillRect,A.f=A.fill,A.p=A.beginPath,A.w=A.arc}if(t==2)with(a=H.A)for(H[c="width"]=I[c]=X,c=0;b=V[c++];)with(b){b.r=0.5+P(0,y)/Y;f(p(a[W]="#df0"),w(x,y,1,0,R));d=(30+U*10)*r;with(a=I.A)f(w(x+U,y+U,d,0,R,p(e=createRadialGradient(x,y,d*0.1,x,y,d*0.8),e[d="addColorStop"](0,A(0,0,0,0.6),e[d](1,A(0,0,0,0))),a[W]=e))),c^1?0:f(a.globalCompositeOperation="xor",r(0,0,X,Y,p(a[W]=A(0,0,20,0.9))));b.x+=N(z,b.y+=O(z,b.t+=U*0.2)*s)*s}if(t==1)for(b=0;e=V[b++];)if((c=e.x-a.clientX)*c+(d=e.y-a.clientY)*d<9E3)e.z=-Q*M,e.s=5;return t^3?t^0?e:"rgba("+[a,b,c,d]+")":Q-0.5}}(t++);with(Math)M=PI,N=cos,O=sin,P=max,Q={valueOf:random};V=[];S=13;U={valueOf:D};c.width=X=innerWidth;Z=(c.height=Y=innerHeight)/4;with(a=E(c).A){for(m=0,i=Z;i<2*Y;i+=4){if(m<S)V[m++]={x:Q*X,y:j=Z+Q*(Y-Z),z:Q*(R=M*2),s:0.4};i^Z?f(w(Q*X,Q*Z,1,0,R,p(a[W]="#fff"))):r(0,Z,X,Y,a[W="fillStyle"]="#120");for(k=0.1*i/Z,j=0;f(moveTo(j,l=i+U*8,p(a[W]=A(0,255,0,0.2+Q*0.4))),bezierCurveTo(j+U*3,l-9*k*(1+U),j+U*6,l-36*k*(1+U),j+U*9,l-81*k*(1+U))),j<X;j+=(8+U)*k);}H=E(c,I=E(c));setInterval(C,S,b.onmousemove=B)};`,
		`for(b.style.cssText="background:#00c;margin:0",c.style.position="fixed",s="ABCDE",t=0;s[t];)self[s[t]]=function(t){return function(a,b,c,d,e){if(t==4){a.parentNode.appendChild(e=a.cloneNode());e.A=e.getContext("2d");with(e)A.r=A.fillRect,A.f=A.fill,A.p=A.beginPath,A.w=A.arc}if(t==2)with(a=H.A){for(H[c="width"]=I[c]=X,c=0;b=V[c++];){with(b){b.r=.5+L.max(0,y)/Y;f(p(a[W]="#df0"),w(x,y,1,0,R));d=(30+U*10)*r;with(a=I.A)f(w(x+U,y+U,d,0,R,p(e=createRadialGradient(x,y,d*.1,x,y,d*.8),e[d="addColorStop"](0,A(0,0,0,.6),e[d](1,A(0,0,0,0))),a[W]=e))),c^1?0:f(a.globalCompositeOperation="xor",r(0,0,X,Y,p(a[W]=A(0,0,20,.9))));b.x+=L.cos(z,b.y+=L.sin(z,b.t+=U*.2)*s)*s}}}if(t==1)for(b=0;e=V[b++];)if((c=e.x-a.clientX)*c+(d=e.y-a.clientY)*d<9e3)e.z=-Q*M,e.s=5;return t^3?t^0?e:"rgba("+[a,b,c,d]+")":Q-.5}}(t++);Q={valueOf:(L=Math).random};V=[];S=13;U={valueOf:D};c.width=X=innerWidth;Z=(c.height=Y=innerHeight)/4;with(a=E(c).A){for(m=0,i=Z;i<2*Y;i+=4){if(m<S)V[m++]={x:Q*X,y:j=Z+Q*(Y-Z),z:Q*(R=(M=L.PI)*2),s:.4};i^Z?f(w(Q*X,Q*Z,1,0,R,p(a[W]="#fff"))):r(0,Z,X,Y,a[W="fillStyle"]="#120");for(k=.1*i/Z,j=0;f(moveTo(j,l=i+U*8,p(a[W]=A(0,255,0,.2+Q*.4))),bezierCurveTo(j+U*3,l-9*k*(1+U),j+U*6,l-36*k*(1+U),j+U*9,l-81*k*(1+U))),j<X;j+=(8+U)*k);}H=E(c,I=E(c));setInterval(C,S,b.onmousemove=B)}`,
		`for(b.style.cssText="background:#00c;margin:0",c.style.position="fixed",s="GTCNO",t=0;s[t];)self[s[t]]=function(t){return function(a,b,c,d,e){if(t==4){a.parentNode.appendChild(e=a.cloneNode());e.G=e.getContext("2d");with(e)G.r=G.fillRect,G.f=G.fill,G.p=G.beginPath,G.w=G.arc}if(t==2)with(a=H.G){for(H[c="width"]=I[c]=X,c=0;b=V[c++];){with(b){b.r=.5+L.max(0,y)/Y;f(p(a[W]="#df0"),w(x,y,1,0,R));d=(30+U*10)*r;with(a=I.G)f(w(x+U,y+U,d,0,R,p(e=createRadialGradient(x,y,d*.1,x,y,d*.8),e[d="addColorStop"](0,G(0,0,0,.6),e[d](1,G(0,0,0,0))),a[W]=e))),c^1?0:f(a.globalCompositeOperation="xor",r(0,0,X,Y,p(a[W]=G(0,0,20,.9))));b.x+=L.cos(z,b.y+=L.sin(z,b.t+=U*.2)*s)*s}}}if(t==1)for(b=0;e=V[b++];)if((c=e.x-a.clientX)*c+(d=e.y-a.clientY)*d<9e3)e.z=-Q*M,e.s=5;return t^3?t^0?e:"rgba("+[a,b,c,d]+")":Q-.5}}(t++);Q={valueOf:(L=Math).random};V=[];S=13;U={valueOf:N};c.width=X=innerWidth;Z=(c.height=Y=innerHeight)/4;with(a=O(c).G){for(m=0,i=Z;i<2*Y;i+=4){if(m<S)V[m++]={x:Q*X,y:j=Z+Q*(Y-Z),z:Q*(R=(M=L.PI)*2),s:.4};i^Z?f(w(Q*X,Q*Z,1,0,R,p(a[W]="#fff"))):r(0,Z,X,Y,a[W="fillStyle"]="#120");for(k=.1*i/Z,j=0;f(moveTo(j,l=i+U*8,p(a[W]=G(0,255,0,.2+Q*.4))),bezierCurveTo(j+U*3,l-9*k*(1+U),j+U*6,l-36*k*(1+U),j+U*9,l-81*k*(1+U))),j<X;j+=(8+U)*k);}H=O(c,I=O(c));setInterval(C,S,b.onmousemove=T)}`,
		`for(b.style.cssText="background:#00c;margin:0",c.style.position="fixed",s="GTCNO",t=0;s[t];)self[s[t]]=function(t){return function(a,b,c,d,e){if(t==4){a.parentNode.appendChild(e=a.cloneNode());e.G=e.getContext("2d");with(e)G.r=G.fillRect,G.f=G.fill,G.p=G.beginPath,G.w=G.arc}if(t==2)with(a=ca.G){for(ca[c="width"]=cb[c]=X,c=0;b=V[c++];){with(b){b.r=.5+M.max(0,y)/Y;f(p(a[W]="#df0"),w(x,y,1,0,R));d=(30+U*10)*r;with(a=cb.G)f(w(x+U,y+U,d,0,R,p(e=createRadialGradient(x,y,d*.1,x,y,d*.8),e[d="addColorStop"](0,G(0,0,0,.6),e[d](1,G(0,0,0,0))),a[W]=e))),c^1?0:f(a.globalCompositeOperation="xor",r(0,0,X,Y,p(a[W]=G(0,0,20,.9))));b.x+=M.cos(z,b.y+=M.sin(z,b.t+=U*.2)*s)*s}}}if(t==1)for(b=0;e=V[b++];)if((c=e.x-a.clientX)*c+(d=e.y-a.clientY)*d<9e3)e.z=-Q*P,e.s=5;return t^3?t^0?e:"rgba("+[a,b,c,d]+")":Q-.5}}(t++);Q={valueOf:(M=Math).random};V=[];S=13;U={valueOf:N};c.width=X=innerWidth;Z=(c.height=Y=innercaeight)/4;with(a=O(c).G){for(m=0,i=Z;i<2*Y;i+=4){if(m<S)V[m++]={x:Q*X,y:j=Z+Q*(Y-Z),z:Q*(R=(P=M.Pcb)*2),s:.4};i^Z?f(w(Q*X,Q*Z,1,0,R,p(a[W]="#fff"))):r(0,Z,X,Y,a[W="fillStyle"]="#120");for(k=.1*i/Z,j=0;f(moveTo(j,l=i+U*8,p(a[W]=G(0,255,0,.2+Q*.4))),bezierCurveTo(j+U*3,l-9*k*(1+U),j+U*6,l-36*k*(1+U),j+U*9,l-81*k*(1+U))),j<X;j+=(8+U)*k);}ca=O(c,cb=O(c));setcbnterval(C,S,b.onmousemove=T)}`,
		`for(b.style.cssText="background:#00c;margin:0",c.style.position="fixed",s="GTCNO",t=0;s[t];)self[s[t]]=function(t){return function(a,b,c,d,e){if(t==4){a.parentNode.appendChild(e=a.cloneNode());e.G=e.getContext("2d");with(e)G.r=G.fillRect,G.f=G.fill,G.p=G.beginPath,G.w=G.arc}if(t==2)with(a=H.G){for(H[c="width"]=I[c]=X,c=0;b=V[c++];){with(b){b.r=.5+M.max(0,y)/Y;f(p(a[W]="#df0"),w(x,y,1,0,R));d=(30+U*10)*r;with(a=I.G)f(w(x+U,y+U,d,0,R,p(e=createRadialGradient(x,y,d*.1,x,y,d*.8),e[d="addColorStop"](0,G(0,0,0,.6),e[d](1,G(0,0,0,0))),a[W]=e))),c^1?0:f(a.globalCompositeOperation="xor",r(0,0,X,Y,p(a[W]=G(0,0,20,.9))));b.x+=M.cos(h,b.y+=M.sin(h,b.t+=U*.2)*s)*s}}}if(t==1)for(b=0;e=V[b++];)if((c=e.x-a.clientX)*c+(d=e.y-a.clientY)*d<9e3)e.h=-Q*P,e.s=5;return t^3?t^0?e:"rgba("+[a,b,c,d]+")":Q-.5}}(t++);Q={valueOf:(M=Math).random};V=[];S=13;U={valueOf:N};c.width=X=innerWidth;Z=(c.height=Y=innerHeight)/4;with(a=O(c).G){for(m=0,i=Z;i<2*Y;i+=4){if(m<S)V[m++]={x:Q*X,y:Z+Q*(Y-Z),h:Q*(R=(P=M.PI)*2),s:.4};i^Z?f(w(Q*X,Q*Z,1,0,R,p(a[W]="#fff"))):r(0,Z,X,Y,a[W="fillStyle"]="#120");for(k=.1*i/Z,h=0;f(moveTo(h,l=i+U*8,p(a[W]=G(0,255,0,.2+Q*.4))),bezierCurveTo(h+U*3,l-9*k*(1+U),h+U*6,l-36*k*(1+U),h+U*9,l-81*k*(1+U))),h<X;h+=(8+U)*k);}H=O(c,I=O(c));setInterval(C,S,b.onmousemove=T)}`,
		`for(b.s5~.cT~="b10~:#00c;m6~:0",c.s5~.p8~="fixed",s="GTCNO",t=0;s[t];)s4~[s[t]]=function(t){return function(a,b,c,d,e){if(t==4){a.pN~.aC~(e=a.cN~());e.G=e.getCont4~("2d");with(e)G.r=G.f4~RR~,G.f=G.f4~,G.p=G.bP~,G.w=G.arc}if(t==2)with(a=H.G){for(H[c="w5~"]=I[c]=X,c=0;b=V[c++];){with(b){b.r=.5+M.max(0,y)/Y;f(p(a[W]="#df0"),w(x,y,1,0,R));d=(30+U*10)*r;with(a=I.G)f(w(x+U,y+U,d,0,R,p(e=cRG~(x,y,d*.1,x,y,d*.8),e[d="addColorStop"](0,G(0,0,0,.6),e[d](1,G(0,0,0,0))),a[W]=e))),c^1?0:f(a.gCO~="xor",r(0,0,X,Y,p(a[W]=G(0,0,20,.9))));b.x+=M.cos(h,b.y+=M.sin(h,b.t+=U*.2)*s)*s}}}if(t==1)for(b=0;e=V[b++];)if((c=e.x-a.clientX)*c+(d=e.y-a.clientY)*d<9e3)e.h=-Q*P,e.s=5;return t^3?t^0?e:"rgba("+[a,b,c,d]+")":Q-.5}}(t++);Q={v5~Of:(M=Math).random};V=[];S=13;U={v5~Of:N};c.w5~=X=iW~;Z=(c.h6~=Y=iH~)/4;with(a=O(c).G){for(m=0,i=Z;i<2*Y;i+=4){if(m<S)V[m++]={x:Q*X,y:Z+Q*(Y-Z),h:Q*(R=(P=M.PI)*2),s:.4};i^Z?f(w(Q*X,Q*Z,1,0,R,p(a[W]="#fff"))):r(0,Z,X,Y,a[W="f4~Style"]="#120");for(k=.1*i/Z,h=0;f(mT~(h,l=i+U*8,p(a[W]=G(0,255,0,.2+Q*.4))),bCT~(h+U*3,l-9*k*(1+U),h+U*6,l-36*k*(1+U),h+U*9,l-81*k*(1+U))),h<X;h+=(8+U)*k);}H=O(c,I=O(c));sI~(C,S,b.o11~=T)}`,
		`for(b.style.cssText="background:#00c;margin:0",c.style.position="fixed",s="GTCNO",t=0;s[t];)self[s[t]]=function(t){return function(a,b,c,d,e){if(t==4){a.parentNode.appendChild(e=a.cloneNode());e.G=e.getContext("2d");with(e)G.r=G.fillRect,G.f=G.fill,G.p=G.beginPath,G.w=G.arc}if(t==2)with(a=H.G){for(H[c="width"]=I[c]=X,c=0;b=V[c++];){with(b){b.r=.5+.1*Q;f(p(a[W]="#df0"),w(x,y,1,0,R));d=(30+U*10)*r;with(a=I.G)f(w(x+U,y+U,d,0,R,p(e=createRadialGradient(x,y,d*.1,x,y,d*.9),e[d="addColorStop"](0,G(0,0,0,.5),e[d](1,G(0,0,0,0))),a[W]=e))),c^1?0:f(a.globalCompositeOperation="xor",r(0,0,X,Y,p(a[W]=G(0,0,20,.9))));b.x+=M.cos(h,b.y+=M.sin(h,b.t+=U*.2)*s)*s}}}if(t==1)for(b=0;e=V[b++];)if((c=e.x-a.clientX)*c+(d=e.y-a.clientY)*d<9e3)e.h=-Q*P,e.s=5;return t^3?t^0?e:"rgba("+[a,b,c,d]+")":Q-.5}}(t++);Q={valueOf:(M=Math).random};V=[];S=12;U={valueOf:N};c.width=X=innerWidth;Z=(c.height=Y=innerHeight)/4;with(a=O(c).G){for(m=0,i=Z;i<2*Y;i+=4){if(m<S)V[m++]={x:Q*X,y:Z+Q*(Y-Z),h:Q*(R=(P=M.PI)*2),s:.4};i^Z?f(w(Q*X,Q*Z,1,0,R,p(a[W]="#fff"))):r(0,Z,X,Y,a[W="fillStyle"]="#120");for(k=.1*i/Z,h=0;f(moveTo(h,l=i+U*9,p(a[W]=G(0,255,0,.1+Q*.5))),d=3,e=3,bezierCurveTo((d+=3)*U+h,l-k*(1+U)*(e*=3),(d+=3)*U+h,l-k*(1+U)*(e*=3),(d+=3)*U+h,l-k*(1+U)*(e*=3))),h<X;h+=(9+U)*k)}H=O(c,I=O(c));setInterval(C,S,b.onmousemove=T)}`,
		`G=function(a,b,c,d,e){return"rgba("+[a,b,c,d]+")"};O=function(a,b,c,d,e){a.parentNode.appendChild(b=a.cloneNode()),b.G=e.getContext("2d");return b};b.style.cssText="background:#00c;margin:0";c.style.cssText="position:fixed";X=[];c.width=innerWidth;N=(c.height=innerHeight)/3;with(a=O(c).G){H=O(c);I=O(c);for(c=0,i=N;i<2*innerHeight;i+=5){if(c<15)X[c++]={x:Math.random()*innerWidth,y:N+Math.random()*(innerHeight-N),h:Math.random()*(R=(P=Math.PI)*2),s:.5};i^N?fill(beginPath(a.fillStyle="#fff"),arc(Math.random()*innerWidth,Math.random()*N,1,0,R)):fillRect(0,N,innerWidth,innerHeight,a.fillStyle="#120");for(k=.1*i/N,h=0;fill(beginPath(a.fillStyle=G(0,255,0,.1+Math.random()*.5)),moveTo(h,l=i+(Math.random()-.5)*8),d=3,e=3,bezierCurveTo((d+=3)*(Math.random()-.5)+h,l-k*(1+(Math.random()-.5))*(e*=3),(d+=3)*(Math.random()-.5)+h,l-k*(1+(Math.random()-.5))*(e*=3),(d+=3)*(Math.random()-.5)+h,l-k*(1+(Math.random()-.5))*(e*=3))),h<innerWidth;h+=(8+(Math.random()-.5))*k);}setInterval(function(a,b,c,d,e){with(a=H.G){H.width=innerWidth;I.width=innerWidth;for(c=0;b=X[c++];){b.r=.5+.1*(Math.random()-.5);fill(beginPath(a.fillStyle="#fff"),arc(b.x,b.y,1,0,R));d=(30+(Math.random()-.5)*10)*b.r;with(a=I.G)e=createRadialGradient(b.x,b.y,d*.2,b.x,b.y,d),e.addColorStop(0,G(0,0,0,.88)),e.addColorStop(1,G(0,0,0,0)),fill(beginPath(a.fillStyle=e),arc(b.x+(Math.random()-.5),b.y+(Math.random()-.5),d,0,R)),c^1?0:fill(beginPath(a.fillStyle=G(0,0,20,.8),a.globalCompositeOperation="xor"),fillRect(0,0,innerWidth,innerHeight));b.x+=Math.cos(b.h)*b.s;b.y+=Math.sin(b.h)*b.s;b.t+=.2*(Math.random()-.5)}}},40,b.onmousemove=function(a,b,c,d,e){for(c=0;b=X[c++];)if((d=b.x-a.clientX)*d+(e=b.y-a.clientY)*e<1e4)b.h=-Math.random()*P,b.s=5})}`,
		`for(b.style.cssText="background:#00c;margin:0",c.style.cssText="position:fixed",s="GTCO",t=0;s[t];)self[s[t]]=function(t){return function(a,b,c,d,e){if(t==3)a.parentNode.appendChild(e=a.cloneNode()),e.G=e.getContext("2d");if(t==2)with(a=H.G){H.width=X;I.width=X;for(c=0;b=V[c++];){b.r=.5+.1*(Math.random()-.5);fill(beginPath(a.fillStyle="#df0"),arc(b.x,b.y,1,0,R));d=(30+(Math.random()-.5)*10)*b.r;with(a=I.G)e=createRadialGradient(b.x,b.y,d*.1,b.x,b.y,d*.9),e.addColorStop(0,G(0,0,0,.5)),e.addColorStop(1,G(0,0,0,0)),fill(beginPath(a.fillStyle=e),arc(b.x+(Math.random()-.5),b.y+(Math.random()-.5),d,0,R)),c^1?0:fill(beginPath(a.fillStyle=G(0,0,20,.9),a.globalCompositeOperation="xor"),fillRect(0,0,X,Y));b.x+=Math.cos(b.h)*b.s;b.y+=Math.sin(b.h)*b.s;b.t+=.2*(Math.random()-.5)}}if(t==1)for(c=0;b=V[c++];)if((d=b.x-a.clientX)*d+(e=b.y-a.clientY)*e<9e3)b.h=-Math.random()*P,b.s=5;if(t==0)e="rgba("+[a,b,c,d]+")";return e}}(t++);V=[];c.width=X=innerWidth;Z=(c.height=Y=innerHeight)/4;with(a=O(c).G){for(m=0,i=Z;i<2*Y;i+=4){if(m<15)V[m++]={x:Math.random()*X,y:Z+Math.random()*(Y-Z),h:Math.random()*(R=(P=Math.PI)*2),s:.4};i^Z?fill(beginPath(a.fillStyle="#fff"),arc(Math.random()*X,Math.random()*Z,1,0,R)):fillRect(0,Z,X,Y,a.fillStyle="#120");for(k=.1*i/Z,h=0;fill(beginPath(a.fillStyle=G(0,255,0,.1+Math.random()*.5)),moveTo(h,l=i+(Math.random()-.5)*9),d=3,e=3,bezierCurveTo((d+=3)*(Math.random()-.5)+h,l-k*(1+(Math.random()-.5))*(e*=3),(d+=3)*(Math.random()-.5)+h,l-k*(1+(Math.random()-.5))*(e*=3),(d+=3)*(Math.random()-.5)+h,l-k*(1+(Math.random()-.5))*(e*=3))),h<X;h+=(9+(Math.random()-.5))*k);}H=O(c);I=O(c);setInterval(C,40,b.onmousemove=T)}`,
		`G=function(a,b,c,d,e){return"rgba("+[a,b,c,d]+")"};O=function(a,b,c,d,e){a.parentNode.appendChild(b=a.cloneNode()),b.G=b.getContext("2d");return b};b.style.cssText="background:#00c;margin:0";c.style.cssText="position:fixed";X=[];c.width=innerWidth;c.height=innerHeight;with(a=O(c).G){H=O(c);I=O(c);for(c=0,i=N=innerHeight/4;i<2*innerHeight;i+=5){if(c<14)X[c++]={x:Math.random()*innerWidth,y:N+Math.random()*(innerHeight-N),h:Math.random()*(R=(P=Math.PI)*2),s:.5};i^N?fill(beginPath(a.fillStyle="#fff"),arc(Math.random()*innerWidth,Math.random()*N,1,0,R)):fillRect(0,N,innerWidth,innerHeight,a.fillStyle="#120");for(k=.1*i/N,h=0;fill(beginPath(a.fillStyle=G(0,255,0,.1+Math.random()*.5)),moveTo(h,l=i+(Math.random()-.5)*8),d=3,e=3,bezierCurveTo((d+=3)*(Math.random()-.5)+h,l-k*(1+(Math.random()-.5))*(e*=3),(d+=3)*(Math.random()-.5)+h,l-k*(1+(Math.random()-.5))*(e*=3),(d+=3)*(Math.random()-.5)+h,l-k*(1+(Math.random()-.5))*(e*=3))),h<innerWidth;h+=(8+(Math.random()-.5))*k)}setInterval(function(a,b,c,d,e){with(a=H.G){H.width=innerWidth;I.width=innerWidth;for(c=0;b=X[c++];){b.r=.5+.1*(Math.random()-.5);fill(beginPath(a.fillStyle="#ef0"),arc(b.x,b.y,1,0,R));d=(30+(Math.random()-.5)*10)*b.r;with(a=I.G)e=createRadialGradient(b.x,b.y,d*.2,b.x,b.y,d),e.addColorStop(0,G(0,0,0,.8)),e.addColorStop(1,G(0,0,0,0)),fill(beginPath(a.fillStyle=e),arc(b.x+(Math.random()-.5),b.y+(Math.random()-.5),d,0,R)),c^1?0:fill(beginPath(a.fillStyle=G(0,0,20,.9),a.globalCompositeOperation="xor"),fillRect(0,0,innerWidth,innerHeight));b.s=b.y>N?Math.max(b.s*.8,.2+(Math.random()-.5)*.3):3+(Math.random()-.5)*2;b.x+=Math.cos(b.h)*b.s;b.y+=Math.sin(b.h)*b.s;b.t+=.2*(Math.random()-.5)}}},42,b.onmousemove=function(a,b,c,d,e){for(c=0;b=X[c++];)if((d=b.x-a.clientX)*d+(e=b.y-a.clientY)*e<1e4)b.h=-Math.random()*P,b.s=8})}`,
		`b.style.background="#00c";b.style.margin=0;c.style.position="fixed";G=function(a,b,c,d,e){return"rgba("+[a,b,c,d]+")"};O=function(a,b,c,d,e){b.appendChild(c=a.cloneNode()),c.G=c.getContext("2d");return c};X=[];c.width=innerWidth;c.height=innerHeight;with(a=O(c,b).G){H=O(c,b);I=O(c,b);for(c=0,i=N=innerHeight/4;i<2*innerHeight;i+=7){if(c<42)X[c++]={x:Math.random()*innerWidth,y:N+Math.random()*(innerHeight-N),h:Math.random()*(R=(P=Math.PI)*2),s:.5};i^N?fill(beginPath(a.fillStyle="#fff"),arc(Math.random()*innerWidth,Math.random()*N,1,0,R)):fillRect(0,N,innerWidth,innerHeight,a.fillStyle="#050");for(k=.3*i/N,h=0;fill(beginPath(a.fillStyle="#020",a.strokeStyle="#0f0"),moveTo(h,l=i+(Math.random()-.5)*9),d=42,e=3,bezierCurveTo((d+=3)*(Math.random()-.5)+h,l-k*(1+(Math.random()-.5))*(e*=3),(d+=3)*(Math.random()-.5)+h,l-k*(1+(Math.random()-.5))*(e*=3),(d+=3)*(Math.random()-.5)+h,l-k*(1+(Math.random()-.5))*(e*=3)),stroke()),h<innerWidth;h+=(42+(Math.random()-.5))*k);}setInterval(function(a,b,c,d,e){with(a=H.G){H.width=innerWidth;I.width=innerWidth;for(c=0;b=X[c++];){fill(beginPath(a.fillStyle="#ef0"),arc(b.x,b.y,1,0,R));with(a=I.G)e=createRadialGradient(b.x,b.y,2,b.x,b.y,d=(72+(Math.random()-.5))*(b.r=.3+.3*(Math.random()-.5))),e.addColorStop(0,G(0,0,0,.7)),e.addColorStop(.3,G(0,0,0,.2)),e.addColorStop(1,G(0,0,0,0)),fill(beginPath(a.fillStyle=e),arc(b.x+(Math.random()-.5),b.y+(Math.random()-.5),d,0,R)),c^1?0:fill(beginPath(a.fillStyle=G(0,0,20,.93),a.globalCompositeOperation="xor"),fillRect(0,0,innerWidth,innerHeight));b.s=N<b.y?Math.max(b.s,Math.random()-.5)*.7:3+(Math.random()-.5);b.x+=Math.cos(b.h)*b.s;b.y+=Math.sin(b.h)*b.s;b.t+=.2*(Math.random()-.5)}}},42,b.onmousemove=function(a,b,c,d,e){for(c=0;b=X[c++];)if((d=b.x-a.clientX)*d+(e=b.y-a.clientY)*e<1e4)b.h=-Math.random()*P,b.s=9})}`,
	}

	for i, _ := range s {
		z := []byte(s[i])
		s, k, _ := Compress(z)
		u, _ := Uncompress(s, k)
		if bytes.Equal(u, z) == false {
			t.Fatalf("Test failed:\n\n%s\n\n%s\n", string(z), string(u))
		}
	}

}
